import os
import requests
from datetime import datetime
from fli.search import SearchFlights
from fli.models import Airport, FlightSearchFilters, FlightSegment, Airline, SortBy, PassengerInfo, TripType

# --- Configuration ---
ORIGIN = Airport.MIA
DESTINATIONS = [Airport.SDQ, Airport.PUJ, Airport.LRM]
OUT_DATE = "2026-07-17"
IN_DATE = "2026-07-21"
AIRLINES = [Airline.AA, Airline.B6]

def generate_html(data_list):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    cards_html = ""
    for item in data_list:
        cards_html += f"""
        <div class="card">
            <div class="card-header">
                <h2>MIA ✈️ {item['dest']}</h2>
                <span class="dates">{OUT_DATE} to {IN_DATE}</span>
            </div>
            <div class="price-grid">
                <div class="price-item">
                    <span class="label">🔄 Round-Trip</span>
                    <span class="value">{item['rt']}</span>
                </div>
                <div class="price-item">
                    <span class="label">🛫 Outbound</span>
                    <span class="value">{item['out']}</span>
                </div>
                <div class="price-item">
                    <span class="label">🛬 Return</span>
                    <span class="value">{item['ret']}</span>
                </div>
            </div>
        </div>
        """

    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flight Tracker: Miami to Caribbean</title>
        <style>
            :root {{ --teal: #008080; --orange: #ff8c00; --light: #f4f7f6; }}
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #e0f2f1 0%, #fff3e0 100%); margin: 0; padding: 20px; color: #333; min-height: 100vh; }}
            .container {{ max-width: 800px; margin: 0 auto; }}
            header {{ text-align: center; margin-bottom: 40px; }}
            h1 {{ color: var(--teal); font-size: 2.5rem; margin-bottom: 10px; }}
            .last-updated {{ color: #666; font-size: 0.9rem; }}
            .card {{ background: white; border-radius: 15px; box-shadow: 0 10px 20px rgba(0,0,0,0.05); margin-bottom: 25px; overflow: hidden; border-left: 8px solid var(--orange); }}
            .card-header {{ background: #fafafa; padding: 20px; border-bottom: 1px solid #eee; }}
            .card-header h2 {{ margin: 0; color: #444; }}
            .dates {{ color: var(--teal); font-weight: bold; }}
            .price-grid {{ display: grid; grid-template-columns: repeat(3, 1/3); padding: 20px; gap: 10px; }}
            @media (max-width: 600px) {{ .price-grid {{ grid-template-columns: 1fr; }} }}
            .price-item {{ display: flex; flex-direction: column; align-items: center; padding: 10px; border-radius: 8px; background: #f9f9f9; }}
            .label {{ font-size: 0.8rem; color: #888; text-transform: uppercase; margin-bottom: 5px; }}
            .value {{ font-size: 1.1rem; font-weight: bold; color: var(--teal); }}
            footer {{ text-align: center; margin-top: 40px; color: #999; font-size: 0.8rem; }}
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>🌴 Flight Tracker</h1>
                <p class="last-updated">Last checked: {now} (UTC)</p>
            </header>
            <main>
                {cards_html}
            </main>
            <footer>
                Generated by GitHub Actions & fli-library
            </footer>
        </div>
    </body>
    </html>
    """
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_template)

def check_flights():
    search = SearchFlights()
    data_for_web = []

    for dest in DESTINATIONS:
        # Search Round Trip
        rt_filters = FlightSearchFilters(trip_type=TripType.ROUND_TRIP, passenger_info=PassengerInfo(adults=1),
            flight_segments=[FlightSegment(departure_airport=[[ORIGIN, 0]], arrival_airport=[[dest, 0]], travel_date=OUT_DATE),
                             FlightSegment(departure_airport=[[dest, 0]], arrival_airport=[[ORIGIN, 0]], travel_date=IN_DATE)],
            airlines=AIRLINES, sort_by=SortBy.CHEAPEST)
        rt = search.search(rt_filters)
        
        # Search One Ways
        out_filters = FlightSearchFilters(trip_type=TripType.ONE_WAY, passenger_info=PassengerInfo(adults=1),
            flight_segments=[FlightSegment(departure_airport=[[ORIGIN, 0]], arrival_airport=[[dest, 0]], travel_date=OUT_DATE)], airlines=AIRLINES)
        out_ow = search.search(out_filters)

        in_filters = FlightSearchFilters(trip_type=TripType.ONE_WAY, passenger_info=PassengerInfo(adults=1),
            flight_segments=[FlightSegment(departure_airport=[[dest, 0]], arrival_airport=[[ORIGIN, 0]], travel_date=IN_DATE)], airlines=AIRLINES)
        in_ow = search.search(in_filters)

        data_for_web.append({
            'dest': dest.name,
            'rt': f"${rt[0][0].price} ({rt[0][0].legs[0].airline.value})" if rt else "N/A",
            'out': f"${out_ow[0].price} ({out_ow[0].legs[0].airline.value})" if out_ow else "N/A",
            'ret': f"${in_ow[0].price} ({in_ow[0].legs[0].airline.value})" if in_ow else "N/A"
        })

    generate_html(data_for_web)

if __name__ == "__main__":
    check_flights()
